name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Chrome using Chocolatey
        run: choco install googlechrome -y

      - name: Download and Install Chrome Remote Desktop
        run: |
          $Path = "$env:TEMP\chromeremotedesktophost.msi"
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $Path
          Start-Process -FilePath msiexec.exe -ArgumentList "/i", $Path, "/quiet", "/norestart" -Wait
          if (!(Test-Path "C:\Program Files (x86)\Google\Chrome Remote Desktop")) {
            Write-Error "Chrome Remote Desktop installation failed."
            exit 1
          }

      - name: Enable Remote Desktop
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - name: Verify Chrome Remote Desktop Installation
        run: dir "C:\Program Files (x86)\Google\Chrome Remote Desktop"

      - name: Configure Chrome Remote Desktop
        run: |
          & "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="$Env:CRD_AUTH_CODE" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="GitHubActionsVM" --pin=123456
        env:
          CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}

      - name: Set Local User Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Open Firewall for Remote Desktop
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Keep Session Active
        run: |
          Write-Host "Press Ctrl+C to terminate..."
          Start-Sleep -Seconds 86400

