name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Chrome
        run: |
          $Path = "$env:TEMP\chrome_installer.exe"
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile $Path
          Start-Process -FilePath $Path -ArgumentList "/silent /install" -Wait

      - name: Download Chrome Remote Desktop
        run: |
          $Path = "$env:TEMP\chromeremotedesktop.msi"
          Invoke-WebRequest -Uri "https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb" -OutFile $Path
          Start-Process -FilePath msiexec.exe -ArgumentList "/i", $Path, "/quiet", "/norestart" -Wait

      - name: Enable Remote Desktop
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - name: Configure Chrome Remote Desktop
        run: |
          & "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\chrome-remote-desktop-host.exe" --code="$Env:CRD_AUTH_CODE" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="GitHubActionsVM"
        env:
          CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}

      - name: Set Local User Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Open Firewall for Remote Desktop
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
